import { NextRequest, NextResponse } from "next/server";
import {
  COOKIE_NAME,
  SESSION_COOKIE_OPTIONS,
  makeSessionToken,
  makeCoHostSessionToken,
  sessionNeedsRenewal,
  verifySessionToken,
  verifyCoHostSession,
} from "@/lib/auth/session";

// Single-user auth gate (Next 16 "proxy" — formerly "middleware"). Runs before
// routes on the Node.js runtime.
//
// Routes reachable WITHOUT a session; everything else requires login:
//   - /book + its APIs: the public booking flow (strangers book the owner's time)
//   - /manage/*: attendee self-serve reschedule/cancel (gated by its own
//     per-booking HMAC token, so it needs no session)
//   - /privacy, /terms: static legal pages — must be publicly fetchable for
//     Google/Microsoft OAuth app verification
//   - /api/oauth/*: provider redirects/callbacks (own CSRF via state param)
//   - /api/sms/*: Twilio inbound webhook (own signature validation)
//   - /api/cron/*: scheduled jobs (own CRON_SECRET bearer)
//   - /login + /api/login + /api/logout: the auth flow itself
// /sitemap.xml is generated by src/app/sitemap.ts (a route, so the static-asset
// matcher exemption doesn't cover it) and must be publicly crawlable.
const PUBLIC_PATHS = new Set(["/login", "/sitemap.xml"]);
const PUBLIC_PREFIXES = [
  "/book",
  "/demo",
  "/assistant",
  "/manage/",
  "/privacy",
  "/terms",
  "/api/login",
  "/api/logout",
  // Liveness probe. Unauthenticated on purpose so external monitors and the
  // pre-push check can poll it; it reports only ok/fail per subsystem.
  "/api/health",
  // "Sign in with Google" — must be reachable with no session, since it is how
  // a session is obtained. It grants nothing on its own: the callback issues a
  // cookie only for a Google-verified address on the owner allowlist.
  "/api/auth/",
  "/api/agent/public",
  "/api/agent/negotiate",
  "/api/agent/requester",
  "/api/agent/demo",
  "/api/availability",
  "/api/public/",
  "/api/oauth/",
  "/api/sms/",
  // Slack Events API. Public because Slack calls it unauthenticated; it does
  // its OWN auth (HMAC signature over the raw body + a replay window), and the
  // sender's Slack id decides whether the private or public agent answers.
  "/api/slack/",
  "/api/cron/",
  "/api/monitor/",
  // MCP server for external agents. Public by design: it does its OWN two-tier
  // auth (public tools unauthenticated; private tools require MCP_TOKEN), so
  // the session gate must not block it.
  "/api/mcp",
];

// Run on everything except Next internals and static assets.
//
// SECURITY: /api/:path* is listed FIRST and unconditionally. The page pattern
// below exempts any path ending in a static-asset extension, and that exemption
// used to swallow API routes too — so `PATCH /api/todos/<id>.js` skipped this
// gate entirely and ran the route handler UNAUTHENTICATED (verified in prod:
// `.js` returned the handler's 404 while the bare path correctly returned 401).
// Only cuid ids and the absence of GET on [id] routes kept it from leaking data,
// i.e. the control was broken and the mitigation accidental. An API route must
// never be treated as a static asset — keep these two matchers separate.
export const config = {
  matcher: [
    "/api/:path*",
    "/((?!api|_next/static|_next/image|favicon.ico|.*\\.(?:png|jpg|jpeg|gif|svg|ico|webp|css|js|map|txt|woff2?)$).*)",
  ],
};

// Routes an authenticated CO-HOST may reach. Everything else stays owner-only:
// a co-host session is rejected outside this set (see proxy()). Keep this narrow
// — it is the privacy wall between a co-host and the owner's dashboard.
const CO_HOST_PREFIXES = ["/cohost", "/api/cohost/"];

function isCoHostRoute(pathname: string): boolean {
  // Same boundary-safe matching as isPublic: "/cohost" covers "/cohost" and
  // "/cohost/...", never a sibling like "/cohostsettings".
  return CO_HOST_PREFIXES.some((p) =>
    p.endsWith("/") ? pathname.startsWith(p) : pathname === p || pathname.startsWith(p + "/")
  );
}

function isPublic(pathname: string): boolean {
  if (PUBLIC_PATHS.has(pathname)) return true;
  // Boundary-safe prefix match: "/book" must expose "/book" and "/book/...",
  // never a future sibling like "/bookings-admin". Bare startsWith has already
  // bitten this file once (see the static-asset matcher note below); entries
  // that end in "/" keep plain prefix semantics.
  return PUBLIC_PREFIXES.some((p) =>
    p.endsWith("/") ? pathname.startsWith(p) : pathname === p || pathname.startsWith(p + "/")
  );
}

export async function proxy(req: NextRequest): Promise<NextResponse> {
  const { pathname } = req.nextUrl;
  if (isPublic(pathname)) return NextResponse.next();

  const secret = process.env.PRIVATE_AUTH_SECRET;
  // No secret configured (local dev) → app is open, unchanged. Production always
  // sets PRIVATE_AUTH_SECRET, so the gate is active there.
  if (!secret) return NextResponse.next();

  const token = req.cookies.get(COOKIE_NAME)?.value;
  const nowSeconds = Math.floor(Date.now() / 1000);
  if (await verifySessionToken(secret, token, nowSeconds)) {
    const res = NextResponse.next();
    // Sliding session: once the cookie is past its halfway point, re-issue it so
    // continued use keeps you logged in indefinitely. Fresh cookies are left
    // alone to avoid re-signing on every single request.
    if (sessionNeedsRenewal(token, nowSeconds)) {
      const fresh = await makeSessionToken(secret, nowSeconds);
      res.cookies.set(COOKIE_NAME, fresh, SESSION_COOKIE_OPTIONS);
    }
    return res;
  }

  // Co-host session → co-host-scoped routes only. Owner-only routes above have
  // already rejected this token (verifySessionToken returns false for the
  // three-segment co-host shape), so a co-host can never reach the dashboard.
  const coHostId = await verifyCoHostSession(secret, token, nowSeconds);
  if (coHostId) {
    if (isCoHostRoute(pathname)) {
      const res = NextResponse.next();
      if (sessionNeedsRenewal(token, nowSeconds)) {
        const fresh = await makeCoHostSessionToken(secret, nowSeconds, coHostId);
        res.cookies.set(COOKIE_NAME, fresh, SESSION_COOKIE_OPTIONS);
      }
      return res;
    }
    // Signed in as a co-host but reaching for an owner-only route. They ARE
    // logged in, so don't bounce to the sign-in form — send them home. APIs get
    // a 403 (authenticated but not permitted), not a 401.
    if (pathname.startsWith("/api/")) {
      return NextResponse.json({ error: "forbidden" }, { status: 403 });
    }
    const home = req.nextUrl.clone();
    home.pathname = "/cohost";
    home.search = "";
    return NextResponse.redirect(home);
  }

  // Unauthenticated: APIs get a clean 401; pages redirect to the login form.
  if (pathname.startsWith("/api/")) {
    return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  }
  const url = req.nextUrl.clone();
  // The ROOT is the exception: send anonymous visitors to the public booking
  // page, not to the sign-in form.
  //
  // Nobody but the owner has any use for `/`, but it is the URL every crawler,
  // link preview and reputation scanner fetches first — and when it answered
  // "307 → /login", the whole public face of a four-week-old domain was a
  // password prompt. FortiGuard rated the domain Phishing on that shape and
  // upheld it on re-review. The owner still reaches the dashboard at `/` once
  // signed in, and `/login` is still there directly. See docs/REGRESSIONS.md.
  if (pathname === "/") {
    url.pathname = "/book";
    url.search = "";
    return NextResponse.redirect(url);
  }
  url.pathname = "/login";
  url.searchParams.set("next", pathname);
  return NextResponse.redirect(url);
}
